### ISSUE TITLE
copy_to depends on type not specified in docstring

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#88]
The `GenericJob.copy_to` docstrings claim that the `project` argument is of type `ProjectHDFio`, but when passed an argument of this time raises an `AttributeError` because this class does not have access to the `job_table` method.

Minimum working example:
```python
from pyiron_base import Project
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)
from pyiron_base.job.generic import GenericJob
job = pr.create_job(GenericJob, 'job')
print(type(job._hdf5))

> <class 'pyiron_base.generic.hdfio.ProjectHDFio'>

print(job.copy_to.__doc__.split('\n')[4])

> project (ProjectHDFio): The project to copy the job to. (Default is None, use the same project.)

copied = job.copy_to(project=job._hdf5)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-fa95e13baac0> in <module>
----> 1 copied = job.copy_to(project=job._hdf5)

~/Liam/pyiron/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in copy_to(self, project, new_job_name, input_only, new_database_entry, delete_existing_job)
    515         project = project or self.project
    516         new_job_name = new_job_name or self.job_name
--> 517         job_table = project.job_table(recursive=False)
    518         if len(job_table) > 0 and new_job_name in job_table.job.values:
    519             if not delete_existing_job:

AttributeError: 'ProjectHDFio' object has no attribute 'job_table'
```

**Comment by jan-janssen** [comment]
I guess this bug was introduced in https://github.com/pyiron/pyiron_base/pull/80

**Comment by liamhuber** [comment]
Yes, I believe so. But I feel that 'copy_to' is pretty foundational and it's getting frustrating how broken it is... maybe we can discuss it tomorrow if there is time.

**Comment by liamhuber** [comment]
Fixed in #89
